<tr> 
    <td width="162" bgcolor="#006699"><b>
      <p align="center"><a href = "http://masterboy.amelieonline.net/adminis/">ADMIN</a></b><br>
    </td>
    <td width="483" bgcolor="#006699">Le site non-officiel Fran&ccedil;ais de 
      Masterboy.<br>
      A ce jour le site Francophone le plus complet du groupe.</td>
    <td width="226" bgcolor="#006699">
      <div align="center"><b></b></div>
    </td>
  </tr>